[build]
compiler = "clang++"

[[targets]]
name = "lglava"
src = "./src/"
include_dir = "./src/include/"
type = "exe"
cflags = " -g -Wall -Wextra"
libs = "-lm -lGLEW -lglfw -lGL -lasound -lX11"
deps = [""]
