[build]
compiler = "clang++"

[[targets]]
name = "lglava"
src = "./src/"
include_dir = "./src/include/"
type = "exe"
cflags = "-O3 -Wall -Wextra -std=c++17"
libs = "-lm -lGLEW -lglfw -lGL -lX11 -lpulse -lpulse-simple"
deps = [""]
